// Copyright (c) 2015-2017, XMOS Ltd, All rights reserved
#ifndef DEBUG_CONF_H_
#define DEBUG_CONF_H_

#define DEBUG_PRINT_ENABLE      1
#define DEBUG_PRINT_ENABLE_ALL 1
#define DEBUG_PRINT_DISABLE_ETHERNET_CLIENT_HANDLER 1
#define DEBUG_PRINT_DISABLE_ETHERNET_FILTER 1

#endif /* DEBUG_CONF_H_ */
